### ISSUE TITLE
Put source code in the repository

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-wpss#1]
@irwink Could you please put the WPSS source code in the repository? It's good that it is available as a zip but people won't be able to fork and help improve it if the source code isn't in the repository.

Make sure to just put the source code and the license file in the repository. Should avoid putting binary files in the repository and leave that to the zip file (unless absolutely need to version the binary files).

**Comment by jpmckinney** [comment]
I'll add my voice to using this as the master repository and pushing all changes to it regularly. It's hard to collaborate if there are unknown changes on a local repository. This can lead to duplication of effort, conflicting changes, etc. If the local is SVN, then as @benbalter described, you can just change the endpoint and continue working as before. If there's a concern about network connectivity, then switching to Git is an option.

**Comment by andrewnordlund** [comment]
Looks like it's been a few years since anyone has commented.

Has anything further come of this?
