### ISSUE TITLE
H57 throwing false failure?

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#103]
It seems H57 is throwing a language fault. Perhaps its because the polyfill classes above it are complicated??

``` <html xmlns="http://www.w3.org/1999/xhtml" class="js svg cssgradients multiplebgs opacity csspointerevents rgba pointerevents hsla supports no-touchevents fontface generatedcontent textshadow cssanimations backgroundsize borderimage borderradius boxshadow csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox no-flexboxtweener cssreflections csstransforms csstransforms3d csstransitions" lang="en" xml:lang="en" dir="ltr" style="visibility: visible;">```

It gave me this error:

ACC | https://www.makeupforever.com/us/en-us/user/login?destination=/us/en-us/learn/how-to/glow-getter | WCAG_2.0-H57 | 3.1.1 H57:   Using language attributes on the html element | -1 | -1 | -1 |   | Unable to determine content language,   possible languages are eng, ger | https://www.w3.org/TR/WCAG20-TECHS/H57
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by irwink** [comment]
The check only looks at what appears to be content made available to the user (e.g. visible content, off screen content) and excludes all supporting tag content (e.g. script tags).  In this case the tool finds about 6000 characters that are within tags having lang="en".  It then checks the content against a number of languages to determine the best fit.  This page yields very similar scores for English and  German, so the tool cannot determine the actual language.  The closeness of scores is influenced by the number of characters and the actual words used.  Words that appear in or are very similar multiple languages would result in close scores.  There isn't much that can be done in this case as there are enough characters to reasonable determine the language, just that the actual words in use are not language specific enough.

**Comment by irwink** [comment]
To eliminate possible false errors, the tool will be changed to not report an error if the content language cannot be determined.

**Comment by irwink** [comment]
Change included in version 6.11.0
