### ISSUE TITLE
Rule Set

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#105]
thought these lists of auto WCAG tests might be helpful

https://dequeuniversity.com/rules/axe/3.0/
All the rules for Axe Core automated checker.

Here's the FAE ruleset
https://fae.disability.illinois.edu/rulesets/

Might want to pick through see if any tests are interesting.

**Comment by irwink** [comment]
Would you see these rules sets being selectable as different profiles (i.e. WCAG 2.0, or AXE or FAE)?  There is a fair amount of overlap in these, so multiple errors for the same problems would not be very usable.

Currently the Government of Canada standard is WCAG 2.0 only, so I would not be mixing these tests under that testcase profile.

**Comment by DavidMacDonald** [comment]
Here's the Pa11y set which is also pretty popular
https://github.com/pa11y/pa11y
@irwink 

AN AXE tool set would be amazing. The API is useful because they have all the help information already completed. SO the CSV output would be their set.

I wouldn't make a specific FAE ruleset. I think I'd just pick through and consider adding to WCAG any checks you don't have.

Pa11y is an API and I think that would be a good idea to use its API also.

**Comment by DavidMacDonald** [comment]
I think having a dropdown to choose the ruleset would be amazing.
1) WPSS ruleset
2) Axe Rule set
3) Pa11y rule set

Yes, there is overlap in these rule sets, but these wouldn't be run all at once. The AXE rule set has a large community of support, and a major accessibility company behind it. Using your spider engine with the AXE rule set would have tremendous value.

**Comment by irwink** [comment]
The implementation will allow you to select the accessibility rule set
- WCAG 2.0
- Deque AXE
- All (WCAG 2.0 + Deque AXE)

I will look at Pa11y and add it similar to the above.

**Comment by irwink** [comment]
Testcase profiles for Deque AXE (51 of 85 rules either completely or partially implemented) and Pa11y included version 6.11.0.

**Comment by DavidMacDonald** [comment]
Wohoooo
