### ISSUE TITLE
PhantomJS Headless is archived, dead product

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#106]
https://semaphoreci.com/blog/2018/03/27/phantomjs-is-dead-use-chrome-headless-in-continuous-integration.html

The recommendation is to use Chrome instead.

**Comment by shawnthompson** [comment]
A lot of Government departments can't use Chrome 👎

**Comment by LaurentGoderre** [comment]
Chromium would be run on CI so not necessarily on GC computers. It's also worth mentioning that if you don't have access to modern tools, chances are you can develop modern solutions.

**Comment by irwink** [comment]
PhantomJS should not be simply replaced as it would have to remain as a fallback for systems that don't have an adequate Chrome installation.
As commented by Shawn, a lot of GC computers are locked down, so they may not have Chrome.

**Comment by DavidMacDonald** [comment]
What about a drop down in the configuration menu to select the headless browser, one would be phantomJS and the other Chrome headless

**Comment by irwink** [comment]
Headless Chrome will be used as headless browser if it is installed on the system.  Requirements are Chrome - version 69 or newer
node - https://nodejs.org/en/download/
puppeteer - https://developers.google.com/web/tools/puppeteer/
If headless chrome is not available, the tool will fallback to PhantomJS.

This will be included in the next WPSS_Tool release.

**Comment by irwink** [comment]
Headless chrome can be used in version 6.11.0.  Fallback to PhantomJS if Chrome is not available.
