### ISSUE TITLE
Consider a failure for more than one <main> landmark or its equivalent

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#107]
Could check if there are more than one `<main>` landmark or `<div role=main>`  as per the spec

https://www.w3.org/TR/html52/grouping-content.html#the-main-element

also 

> Authors must not include the main element as a descendant of an article, aside, footer, header or nav element.

**Comment by irwink** [comment]
This feature was added in version 6.6.0 (Aug 2017).  It checks for multiple combinations of main tags or tags with role="main".  Failures are reported  under WCAG_2.0-SC1.3.1 (I did not see any appropriate common fail or sufficient technique to use).

If you have another instance of multiple mains that is not detected, please provide a description or link to a sample page.

**Comment by DavidMacDonald** [comment]
Does it also check for illegal parents (article, aside, footer, header, nav)?
Which test case number is it, so I can look for it in reports? Thanks.

**Comment by irwink** [comment]
It does not check for illegal parents, that would have to be added.  The errors are reported under testcase WCAG_2.0-SC1.3.1 (the success criterion).

**Comment by DavidMacDonald** [comment]
I suggest adding that check for illegal parents.

**Comment by irwink** [comment]
Check for illegal ancestors to be included in next release.

The list of testcases in the wiki is out of date and on the to-do list.

**Comment by irwink** [comment]
Included in version 6.10.0
