### ISSUE TITLE
Consider adding columns to CSV to provide more AXE metadata

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#110]
I love the new AXE and Pa11y sets. 

AXE tests come with with a number of metadata categories that aren't currently included in the WPSS output results CSV. I think it would be great to add a few columns to the CSV at the end (right side of the spreadsheet). The other rule sets would remain empty in those columns (unless Pa11Y has any similar extra metadata), but for axe they'd be populated. 

1) There is an Axe metadata that provides whether its a WCAG failure or best practice. I think its called "Tags"
2) There is a metadata that identifies the node where the error is by walking the node tree. I think its called "Target"
3) There is an "Impact" category
4) There is a "Description" metadata that has messages something like "Ensure that every form element of the page ..."

There might be a couple of others that are useful also.

**Comment by mgifford** [comment]
This sounds like it would be a useful addition.

**Comment by irwink** [comment]
The next release of the tool will use the command line AXE tool and incorporate the above metadata in the CSV results file.

**Comment by mgifford** [comment]
Thanks @irwink any ETA on that?

**Comment by irwink** [comment]
AXE tags and impact metadata are included in version 6.12.0.
