### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by schindld** [wet-boew/wet-boew-wpss#112]
Is there a version of this that will run GUI-less in linux?

**Comment by irwink** [comment]
Yes the tool can be packaged for Linux.  It is a command line version only (same command line as Windows).  To date I have not packaged and released a Linux version as there was no request.  I do use the Linux version extensively for batch monitoring of web sites.

**Comment by schindld** [comment]
Would you mind publishing it (or the build script) here? I want to use the WPSS tool in a dockerized environment (for automation).

**Comment by irwink** [comment]
Release 6.11.1 has been uploaded, it is a Linux version of 6.11.0.

**Comment by schindld** [comment]
Could you also publish the build script so that I can keep the image up-to-date in the future (clone latest from gitlab, then build the linux version from source)?

And there's a discrepancy in _install.pl_ in the **Check_Java** function. The comment says "Is this Open Java version 11 (major = 11) **or greater**", but the code says `&& ($major == 11)`.

Because of the mess of base image versions of java on docker hub (there's no openjdk 11 alpine for example), can the **Check_Java** function be fixed, or is was it intentional to match only v11?

**Comment by schindld** [comment]
There's also a problem with install.pl. Line 55 refers to Win32::TieRegistry and throws an error.

If I comment out that line, there's an error on lines 204 and 205 about $Registry not being defined. So, I declare $Registry and get past that error.

Then "Python module setuptools not found". I install it. "Python module jsonschema not found". I install it. And finally the install script finishes.

I set up a crawl file, and run `perl wpss_tool.pl -cli -c crawl` and get the TieRegistry.pm module error.

Are you sure the 6.11.1 release (https://github.com/wet-boew/wet-boew-wpss/releases/download/6.11.1/WPSS_Tool_Linux.zip) was built for linux?

**Comment by irwink** [comment]
Is "." in the Perl @INC paths?  There is a Linux version of TieRegistry.pm included with the distribution.  This would solve the install.pl and wpss_tool.pl problems.

Some of the Python dependencies have not been listed, they are present in the Windows Python install.  I have only 1 installation of the tool on Linux, so not all the dependencies have been documented (I installed them as I needed then over time).

**Comment by mgifford** [comment]
I'm assuming that this will also work on MacOS. 

Would love to have non-Windows instructions added to the Readme.md file.

**Comment by irwink** [comment]
Installation instructions for Linux included both in the user guide and the release readme.

**Comment by potatowave** [comment]
> Installation instructions for Linux included both in the user guide and the release readme.

I'm looking for these instructions.  I've checked the user guide.  A text search for 'linux' returns 0.  The readme talks about requirements.  Is that what you're referring to?

I'm not familiar with perl, so would be nice to have some clearer steps to run this tool in Linux.
