### ISSUE TITLE
Wiki's ActivePerl download link

### ISSUE THREAD

**Issue by shnewto** [wet-boew/wet-boew-wpss#113]
:wave: 

I have a suggested edit to the wiki but felt uncomfortable editing without checking in first :upside_down_face:
The wiki's link to the ActivePerl download (in https://github.com/miguelfreitas/twister-core/wiki/Building-twister-with-Visual-Studio-2010) requires a bit more work from the user. It takes a couple extra clicks to get to the download and also ends up "forking" the project from ActiveState, which gives the user ownership of the distribution and the ability to edit it, but that might be overkill if you "just want the download". 

Theses days it's simpler to point straight to https://platform.activestate.com/featured-projects. That lets a user see what they're in for without logging in and also lets them download an ActivePerl that's owned and maintained by ActiveState. 

If you're amenable to the change, I'd be happy to do the editing myself 😄 

Thanks!

**Comment by irwink** [comment]
I have updated the documentation to remove references to ActivateState Perl.  When I tried the latest version of the tool on the latest version of ActiveState Perl, it did not work as some required modules were not available (Win32::GUI) and I could not find a PPM for them.
