### ISSUE TITLE
Document who is using this and why

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-wpss#116]
I asked in GCMessage about this project to see if i could get more background. Do we have any idea who is using the wet-boew-wpss is currently in the GC. Is there critical mass behind it? Is it being effective in helping to identify the 30% of accessibility issues that can be identified with automated tools?

How does this suite of automated tools compare with all of the others out there?

**Comment by irwink** [comment]
Within PSPC the web development team and the Open Government teams use the tool as part of the development and verification process.  This is about 30 people. Based on downloads and issues submitted, the tool is being used by others.

There has not been a full analysis of how the tool compares to other commercial and open source products for several years. Some informal comparisons were favorable, especially when cost is considered.
