### ISSUE TITLE
Consider adding AXE xpath and AXE "Message" field

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#120]
1) I think the AXE API provides the xpath under a field called "element location" or "target". That could be mapped to xpath column in the WPSS.
2) There is a column called "message" in AXE which could come in under the WPSS "message" field

**Comment by irwink** [comment]
Deque AXE command line tool may be used with WPSS_Tool 6.13.0. The fields reported by the WPSS_Tool are limited to those that are returned by the command line tool.
