### ISSUE TITLE
Release installer/archive process documentation

### ISSUE THREAD

**Issue by morvans** [wet-boew/wet-boew-wpss#123]
Hey there,
Thank for the good work and opensourcing it.
Is there any documentation and/or script that allows to understand how the release process work ?
I'm willing to make WPSS work on linux/docker but there's a lot of differences between the repo layout and the released .zip archive.
Is there a way for me to build the .zip from the repo source so I can test how my changes to the source would reflect in a released .zip archive ?

**Comment by irwink** [comment]
This repository only contains the core source code, not all the supporting components. Therefore a full release cannot be built from it at this time. In the next release all the supporting components will be added to the repository along with a build script to built releases.

**Comment by irwink** [comment]
Build scripts and instructions included in repository.
