### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by RababGomaa** [wet-boew/wet-boew-wpss#124]
I tried installing the tool on my windows work laptop and got a message with only option of "Don't run"
"Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk. "Don't Run link""

**Comment by irwink** [comment]
This is caused because this software package is not recognized by windows defender and has no Extended Validation (EV) Code Signing Certificate. You can install the tool by selecting the "More info" link on the defender screen and select the "Run anyway" button.
