### ISSUE TITLE
  Testcase:  1.3.1 H48: Using ol, ul and dl for lists or groups of links Empty ULs in a dropdown Javascript menu

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#25]
There are lots of reasons not to like some dropdown JavaScript menus such as [this one](http://www.ottawapolice.ca/en/home.aspx). But often find 1000 page crawls end up dominated with H48, 100's of instances cause of templates with menus. 

```
Testcase:  1.3.1 H48: Using ol, ul and dl for lists or groups of links
Line: 238 Column:   5
No <li> found in list <ul>
Source line: </ul>
```

There is a dropdown JavaScript menu which has display:none. Seems that the assistive technologies respect that and don't pull up a bunch of empty ULs.

Suggest sniff for a display:none and don't fire the failure if so. (note: this dropdown has other failures such as lack of keyboard access, that I'm not addressing in this issue. Here's the code:

``` html
<div class="rmSlide" style="visibility: visible; height: 108px; width: 174px; display: none; overflow: hidden; left: 0px; top: 42px; z-index: 8;">
<ul class="rmVertical rmGroup rmLevel1" style="display: block; top: 0px; left: 0px; visibility: visible;">
<li class="rmItem rmFirst">
<a class="rmLink" href="CrimeFiles/CrimeMaps_Reports/index.aspx" style="width: 132px;">
<span class="rmText">Crime Mapping Tool</span>
</a>
<div class="rmSlide">
<ul class="rmVertical rmGroup rmLevel2"> </ul>
</div>
</li>
<li class="rmItem ">
<a class="rmLink" href="CrimeFiles/Crimestoppers.aspx" style="width: 132px;">
<span class="rmText">Crime Stoppers</span>
</a>
</li></ul>
</div>
```

**Comment by irwink** [comment]
I think that with using headless user agents to get the generated HTML (after JavaScript has run) and checking for display:none, that this error no longer appears.
