### ISSUE TITLE
Publish to PAUSE/CPAN/PPM

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew-wpss#27]
Have you considered releasing the modules on one of the Perl module archives
http://www.activestate.com/activeperl/ppm-perl-modules
http://www.cpan.org/
https://pause.perl.org/pause/query?ACTION=pause_04about

*Not a Perl developer, just curious

**Comment by mgifford** [comment]
There does seem to be Linux support now according to one of the threads.  Not sure about MacOS. 

That said, this should have been updated since 2013.

**Comment by irwink** [comment]
There is no MacOS support, although I did hear of someone using on Mac several years ago.  I do not have the facilities to test on Mac.

**Comment by mgifford** [comment]
That's too bad.
