### ISSUE TITLE
Try to solve the issue of dissassociating .pl with pearl

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#42]
This process of disassociation of .pl extension type with Pearl is a killer in Win 7 ... perhaps it could be worked out in the installation file... had to install a little hacker file to do it, that made virus scanners complain...

In WIN 8 there was a lot of trouble associating .pl with the WPSS tool... perhaps migrating to a regular .exe eventually could solve this??
Couldn't install in Win 8...so far unsuccessful...

**Comment by mgifford** [comment]
I assume this would have been fixed by now.

**Comment by irwink** [comment]
Yes fixed.
