### ISSUE TITLE
Integrating WPSS into WET build process?

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-wpss#47]
Is there some way of integrating WPSS into the WET build process? Say have it run on every PR and merge like we do with the other checkers and linters? Would be good to have WCAG 2.0 and other checking done automatically. Would need to make sure it doesn't slow build down too much.

@LaurentGoderre @nschonni Any thoughts?

**Comment by mgifford** [comment]
It would be useful to have something like this bundled into the Drupal WxT project too https://github.com/drupalwxt/

That said, I'm kinda thinking that some of this might be better done elsewhere. Is the approach here got a critical mass behind it?

https://www.previousnext.com.au/blog/automate-your-drupal-accessibility-testing-axe-and-nightwatchjs
https://www.fourkitchens.com/blog/development/automated-accessibility-testing-emulsify/
https://blog.dcycle.com/blog/2019-04-07/accessibility/
