### ISSUE TITLE
Provide level of impact for each test

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#51]
Many of the commercial crawlers provide level of impact...
Critical, Serious, Moderate, Minor

Then in the summary they are able to provide a little more information as to the nature of the problems.
1, critical, 4 serious, 256 moderate, 200 minor

This helps prioritize remediation, and cool graphs can be made from the summaries.

I think a level of impact could be assigned to each test... I might be able to help with that.

**Comment by DavidMacDonald** [comment]
Yes I think that would help... and would love a csv...
I will send you an example of my interim eye candy for managers by email...

**Comment by mgifford** [comment]
I like this approach to triaging problems https://accessibility.18f.gov/checklist/
