### ISSUE TITLE
Summary results, add some colons and commas to make it more readable

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#52]
-Current summary result for one test
4.1.1 H94: Ensuring that elements do not contain duplicate attributes
  URLs   116 instances   312  help http://www.w3.org/TR/2010/NOTE-WCAG20-TECHS-20101014/H94
-suggested summary
 4.1.1 H94: Ensuring that elements do not contain duplicate attributes
  URLs:116,  instances: 312,  help: http://www.w3.org/TR/2010/NOTE-WCAG20-TECHS-20101014/H94

The commas might also help analyzing results. I like to pull the summary into Excel and create a table and pie chart of the summary results. Managers like that stuff. Top errors etc...

**Comment by irwink** [comment]
A CSV file of testcase results is provided with version 5.0.0.  This would allow for custom sorting, filtering, charting, etc.
