### ISSUE TITLE
For F2 exempt bold text imediately following a heading

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#56]
F2 looks for big bold text that is short sentence and not part of paragraph etc. It's a great test but gets occasional false failures... one fix could be to look to see if it immediately follows a heading, and not flag it if it does... it's probably a support text for the heading which shouldn't be another heading in many cases. 

For example the text 
By Morgan Davy 
was assigned a false failure here but would not have been flagged if the test looked for a heading immediately above it.
http://www.qnetnews.ca/?p=33360

**Comment by irwink** [comment]
Will check for content after a header or h tag before emphasized text.  If content is found, the emphasized text will not be reported as a pseduo-heading.

**Comment by irwink** [comment]
Bolded or emphasized text immediately after a heading is not reported as a pseudo heading in version 5.0.0.
