### ISSUE TITLE
F43 fails a heading after an <hr>

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#60]
The documentation of f43 says:
```<hr> used as decoration (<hr> followed by another <hr>, or heading followed by <hr>).```
Which I would agree with. But in the actual check it appears to do the opposite, it fails a heading after an hr, which should be fine.

```
  Testcase:  1.3.1 F43: Failure of Success Criterion 1.3.1 due to using structural markup in a way that does not represent relationships in the content
    Line: 1249 Column:   0
    <hr> followed by <h2> used for decoration
    Source line: <h2>
```
Original file that contains this error is here
http://dh.com/fr/expertise/speakers-bureau/best-practices-in-internet-mobile-banking-fraud-protection

It seems like the check does the opposite as its intention.
Suggest amending that part of the check, and allow hr element to be put before any level of heading, but not immediately after.

http://www.w3.org/TR/html5/grouping-content.html#the-hr-element

**Comment by irwink** [comment]
Tool version 4.8.0 now only reports an error if a hr tag precedes a h1 tag.
