### ISSUE TITLE
do PDF18 and F25 overlap?

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#61]
it appears they both check for the title in a pdf document...

if so, I'd drop the pdf check from f25

**Comment by irwink** [comment]
The 2 techniques check different aspects of the title of a PDF.  If there is no title property in the file, PDF18 is reported.  If the title value is an empty string or an invalid string (e.g. "Untitled"), then F25 is reported.  A similar behavior is used for HTML title with respect to H25 and F25.

For PDF documents you should not receive both an PDF18 and F25 error.
