### ISSUE TITLE
G130 should not fail for no links if it's an iframe

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#63]
G130 currently fails a site if there are no links in an iframe on a page. I'd sniff for iFrame and not trigger the error in them.

**Comment by irwink** [comment]
Tool will be changed to report G125 in there are no links and no frame/iframe tags.  The assumption would be that the frame/iframe would contain links to related pages.

**Comment by irwink** [comment]
Corrected in version 5.0.0
