### ISSUE TITLE
Testcase:  1.3.1 G115: Using semantic elements to mark up structure

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew-wpss#65]
Version 4.8.0

This should not be a fail ...

Line:  88 Column:  15
    Missing text in <section>
    Source line: </section>

This is the Actual search box...

```html
<section role="search"><div id="gcwu-srchbx"><h2>Search</h2><form action="https://recherche-search.gc.ca/rGs/s_r" method="get" id="cse-search-box">
<div id="gcwu-srchbx-in">
<input type="hidden" name="st" value="s" />
<input type="hidden" name="s5bm3ts21rch" value="x" />
<input type="hidden" name="st1rt" value="0" />
<input type="hidden" name="langs" value="en" />
<input type="hidden" name="cdn" value="canada" />
<label for="gcwu-srch">Search Web site</label>
<input id="gcwu-srch" name="q" type="search" value="" size="27" maxlength="150" />
<input id="gcwu-srch-submit" type="submit" value="Search" data-icon="search" />
</div>
</form>
</div></section>
```

Can you add a exception for section role=search ...

**Comment by irwink** [comment]
Do you have an example of this appearing on a page ? I did not see this form in the lastest WET 4.0 GCWU or GCWeb themes.

**Comment by crochefort** [comment]
Look at the example here: (scNET only)
http://www.gcpedia.gc.ca/wiki/GC_Web_Search/Adoption_Instructions

This is for the WET3 site.

**Comment by irwink** [comment]
I tried the WET 3 search form in a WET 3.0.5 page and did not get any errors.

**Comment by crochefort** [comment]
Is it possible for me to contact you by email?

**Comment by irwink** [comment]
Sure, kevin.irwin@tpsgc-pwgsc.gc.ca

**Comment by irwink** [comment]
As discussed via email, this will be corrected in the next release.  The script tag inside the div tag was causing the tool to loose content.

**Comment by crochefort** [comment]
Thanks!
