### ISSUE TITLE
Configuration tab

### ISSUE THREAD

**Issue by amandadmills** [wet-boew/wet-boew-wpss#67]
Is there a readme file or something of the sorts that explain all the choices on the Configuration tab?

**Comment by irwink** [comment]
Documentation is provided with the tool installation under the WPSS_Tool<documents folder.  Information is also availbable in the repository at https://github.com/wet-boew/wet-boew-wpss/wiki/WPSS-Validation-Tool-User-Guide#using-the-wpss-validation-tool
