### ISSUE TITLE
Interoperability Testcase:  SWI_C: Character Encoding Requirements is not working when the HTML Attributes are push back further  in the source code

### ISSUE THREAD

**Issue by wet-boew-testing** [wet-boew/wet-boew-wpss#68]
The tool is NOT consistent to find the Character Encoding Requirements

TEST 1 - PASSED
The Interoperability issue is found at http://www.gcsurplus.ca/?urlkey=666999666
Testcase:  SWI_C: Character Encoding Requirements
Line:  12 Column:   1
Charset is not UTF-8
 Source line:meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /

TEST 2 - FAILED
NO Interoperability issue is found at http://www.gcsurplus.ca/mn-eng.cfm

The same issue should have been found in Line:  201 Column:   1

**Comment by irwink** [comment]
In the 2nd case the HTTP header contains a charset of UTF-8.  In both cases the HTML code includes a meta tag specifying a charset of 8859-1.  The check was implemented to look for UTF-8, I hadn't expected there to be 2 charset settings that conflict.  I will add a check for any charset that is not UTF-8 and not stop on the first charset setting.

**Comment by irwink** [comment]
Addressed in version 5.1.0.
