### ISSUE TITLE
F68 fails select boxes for not being wrapped in a form

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#69]
It appear HTML5 identifies Select boxes as "flow content" and not necessarily in a form...
http://www.w3.org/TR/html5/forms.html#the-select-element

Issue 4	1.3.1 F43: Failure of Success Criterion 1.3.1 due to using structural markup in a way that does not represent relationships in the content
http://nexteraenergycanada.com/privacy.shtml 
    Line: 103 Column:  33
    <select> found outside of a <form>
    Source line: <select name="FamilyOfSites" id="select" onchange="window.open(this.options[this.selectedIndex].value,'_self')" style="font: Verdana; font-size: 10px; color: #616161; width: 155px;">

**Comment by irwink** [comment]
The page you reference is XHTML, not HTML5.  Aside from that HTML5, does appear to allow for select elements outside of a form.  If it is outside of a form, then it should have either a JavaScript actions associated with it or a form attribute to associate it with a form somewhere else on the page.  This question could also apply to other elements normally associated with forms, which are checked to see if they are within forms, such as input.

**Comment by irwink** [comment]
This should be addressed in version 5.1.0.
