### ISSUE TITLE
Windows 10 is here... will WPSS work with it?

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#71]
would like to upgrade from 7 with free upgrade but only it WPSS tool works on it.

**Comment by irwink** [comment]
This will require some investigation, I have access to a Windows 10 workstation now.

**Comment by DavidMacDonald** [comment]
Seems to be working fine for me, over the last few months...

**Comment by irwink** [comment]
Closing issue.
