### ISSUE TITLE
I love the new CSV format, couple of suggestions

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#74]
A great option to present information.

It would be great to have the summary section that is in the text report available that way also. Then it would be fairly easy to make glossy dashboards in Excel which managers love.

**Comment by DavidMacDonald** [comment]
recommend putting the Help url in the spreadsheet, then can turn them into urls linked easily.
Not sure what the "page_no" column is, they all seem to be -1

**Comment by irwink** [comment]
The "page_no" column is used for PDF documents.  It indicates which page in the PDF that the error was found in.  Non PDF (e.g. HTML) web pages don't have page numbers, so -1 is used to indicate a not applicable value.

**Comment by DavidMacDonald** [comment]
Oh... OK

**Comment by irwink** [comment]
The next release of the tool will include a help URL in the CSV file for each testcase that points to the relevant WCAG 2.0 technique.

**Comment by irwink** [comment]
Help URL included in CSV file with version 6.0.0.
