### ISSUE TITLE
Advantages of a DOM crawler, rather than code crawler

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#75]
Might be worth exploring.
I understand that a headless browser would be needed for this... this is what is done by the crawler used by the university of Illinois.
http://fae20.cita.illinois.edu/
Also I've provided a review of their tests for WCAG fidelity here
http://davidmacd.com/WCAG/review-of-ruleset-OAA.html
it legislates from the bench quite a bit...

**Comment by irwink** [comment]
A headless user agent (browser) is being integrated into the next tool release.  This provides the WPSS_Tool access to the generated HTML markup, the markup after the initial JavaScript is loaded and run,

**Comment by irwink** [comment]
Version 6.0.0 uses a JavaScript aware headless user agent to get HTML web pages and execute JavaScript when loading.  The generated mark-up is used by the WPSS_Tool when performing checks.
