### ISSUE TITLE
User scalable window disabled, idea for warning/failure

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#78]
<meta name="viewport" content="user-scalable=no, width=1024">
https://dequeuniversity.com/rules/axe/1.1/meta-viewport

**Comment by irwink** [comment]
A check for meta name="viewport" and content with either "user-scalable=no" or "maximum-scale" less than 5.0 will be added.  Failures will be reported under success criterion 1.4.4 - Resize Text.

The check will be added in the next version of the tool.

**Comment by irwink** [comment]
Closing issue as it is solved by issue #83
