### ISSUE TITLE
H51 Table layout

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#81]
I understand table layout is not desired so any table should have headers, because it is assumed to be a data table.

I think this could be tweaked.
If there is `<table role="presentation" ...>` I think this should be a legal use of a layout table, and the error does not kick in. It doesn't cause a screen reader trouble, because it turns the table into a div for the accessibility api

**Comment by irwink** [comment]
Will add check for role="presentation", if found treat the table as a layout table.

**Comment by irwink** [comment]
Check for role="presentation" included in version 6.1.0.  Checks for caption/summary/headers in layout tables also included.
