### ISSUE TITLE
Possible new text check viewport resize not disabled

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#83]
https://dequeuniversity.com/rules/axe/1.1/meta-viewport

**Comment by irwink** [comment]
A check for meta name="viewport" and content with either "user-scalable=no" or "maximum-scale" less than 5.0 will be added.  Failures will be reported under success criterion 1.4.4 - Resize Text.

The check will be added in the next version of the tool.

Note: This is a duplicate of issue #78

**Comment by irwink** [comment]
Check included in version 6.1.0
