### ISSUE TITLE
Potential new test, empty Main element or region

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#84]
I saw this today and thought it would be an easy win for an automated check failure of 1.3.1

```
<section role=main></section>
<div id="content>
```

also these empty main elements
```
<main></main>
```
and
```
<div role=main></div>
```

**Comment by irwink** [comment]
This check will be added to the next release along with a check for multiple main content areas (e.g. multiple <main> tags or multiple tags with role=main).

**Comment by irwink** [comment]
Check added in version 6.6.0 (August 2017)
