### ISSUE TITLE
Consider new test for ARIA children being within parents

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#85]
Certain ARIA roles must be contained by particular parent roles in order to perform the intended accessibility functions.

The Algorithm, in Simple Terms
Checks all elements that contain a WAI-ARIA role to ensure that all required parent roles are present

See https://dequeuniversity.com/rules/axe/2.1/aria-required-parent?application=axeAPI

**Comment by DavidMacDonald** [comment]
I should also add that a check could also be done for required parents.

**Comment by irwink** [comment]
To be included in version 6.9.0

**Comment by irwink** [comment]
Feature added in version 6.9.0.
