### ISSUE TITLE
Identifying template issues.

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#89]
Here's a possible algorithm to identify template.

It basically adds a column (i) to identify template errors and assign rows (issues) to those. So if there were 10 distinct template errors there would be the numbers 1, 2, 3 etc. to 10 in column (i) indicating which template error the issue belonged to. There might be 50 rows with the number 1 in column (i) and 20 rows with the number 2 in column (i) etc.  The algorithm runs after the crawl, and might be something like this:
 
## Chunk 1a – Query a match for rows 2 and 3 for columns C, G, H

* In Row 2 populate 3 variables with the strings from C2, G2, H2.
* Go to Row 3 store 3 variables for strings from C3, G3, H3
* TRUE/FALSE Does C2 = C3 AND G2 = G3 AND H2 to H3
* If TRUE, place the number “1” in Columns I2 and I3
* Dump variables C3, G3, H3 (to save memory, we may have 1000’s of rows)

## Chunk 1b – Query a template match for rows 2 and 4, columns C, G, H

* In row 4 get variables for strings in C4, G4, H4
* TRUE/FALSE Does C2 = C4 AND G2 = G4 AND H2 = H4
* If they all match place the number “1” in I4
* Dump variables C4, G4, H4
* Repeat the above for Row 5, 6, 7, etc. comparing each them to row 2 in turn and adding the value 1 to column I, whenever all three match. Do this until there are no more rows to compare to row 2. Dump variables for Row 2
 
We now have all of the matches for Template error Number 1 and have documented them in column H with the number “1”.

## Chunk 2a – Query a match template error Number 2

* If H3 has a value, move to step 2b else continue 
(ignore rows already matched)
* Get variables for strings in C3, G3, H3
* Move to row 4, IF I4 has a value, ignore row 4 and skip to row 5 ELSE continue
* Get variables for Columns C4, G4, H4
* TRUE/FALSE Does C3 = C4 AND G3 = G4 AND H3 = H4
* If they all match place the number 2 in Columns I3 and I4
* Dump variables for Row 3

Repeat the above for Row 5, 6, 7, etc. comparing each them to row 3 in turn and adding the value 2 to column I for rows where all three match. Do this until there are no more rows to compare to row 3. Dump variables for Row 3

Continue this process until each row has been compared to every other row. And all of the matching rows have respective numbers in the I column identifying the template error (1, 2, 3 etc)
 
## Chunk 3 – Provide 2 user variables to chop x (front) and y (back) number of characters off of column G comparisons

Need to ignore characters from front and back of strings when matching Column G (source code snip) to ensure a match, because the error is in the middle of the string with 50 characters before and after it in the cell. This minimizes problems when the error string straddles part of the template and part of the author content.
 
* Create two variables X and Y
* X is the number of characters at the beginning of each string in column (G) to ignore
* Y is the number of characters at the end of each string in column (G) to ignore
* For example X=10 would cause the tool to ignore 10 characters at front of the string.  Y=15 would cause the tool to ignore 15 characters at the end of the string, for all comparisons involving column G.

**Comment by canasa** [comment]
Disregard previous message. Thanks. -Alex

**Comment by DavidMacDonald** [comment]
My top original issue has the correct columns. This emailed one above was one of my earlier drafts has a few typos in the column letter identifiers.

**Comment by DavidMacDonald** [comment]
I'll close issue because I think its easier to simply identify which landmark role the error is a child of. I filed an issue requesting that.
