### ISSUE TITLE
WPSS Version 6.6.0 - Runtime error

### ISSUE THREAD

**Issue by krlamont** [wet-boew/wet-boew-wpss#91]
Hi  Kevin,

I recently installed WPSS Version 6.6.0. Every time I ran a scan I would get a runtime error before the scan would complete. I tried several different settings and still got the same error message:

**** Runtime Error Analysis Aborted ****
Not a HASH reference at C:/Program Files (x86)/WPSS_Tool/lib/html_check.pm line 12647.

![wpss](https://user-images.githubusercontent.com/8522847/30756436-b69d7916-9f98-11e7-8bc2-97073b97c557.jpg)

Has anyone else reported this issue?

Keith
keith.lamont@tpsgc-pwgsc.gc.ca

System info:
WIN 7 Enterprise
Developer notebook - 64bit OS

**Comment by irwink** [comment]
Fixed in version 6.7.0
