### ISSUE TITLE
Consider adding a column to results to identify container Landmark

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#92]
How hard would it be to look back up the node tree of an error and find the container landmark? Then put that container in a separate column in the CSV.
If the error is a child of one of these landmarks it would be easier to group errors and to separate template issues from content issues:

In HTML the landmark element are:
```<main>```
```<header>```
```<footer>```
```<nav>```
```<aside>```
or the aria role counterparts
```<... role="main">```
```<... role="banner">```
```<... role="contentinfo">```
```<... role="navigation">```
```<... role="complementary">```
```<... role="search">```
Common id values for landmarks
```<div id="content" ... ```
```<div id="main-content" ... ```
```<div id="main" ... ```
```<div id="footer" ... ```
```<div id="header" ... ```
```<div id="navigation" ... ```
```<div id="nav" ... ```

The new column would just be a list of the container landmark code snip next to each issue.

Test_Case | All the other columns | Container Landmark
------------ | ------------- | -------------
F38 | the other columns about the error | ```<footer>```
F43 | the other columns about the error | ```<header>```
F38 | the other columns about the error | ```role="banner```
F43 | the other columns about the error | ```id="content```

**Comment by irwink** [comment]
To be included in version 6.9.0

**Comment by irwink** [comment]
Feature added in version 6.9.0.
