### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-wpss#94]
Please update the README.md link to the strawberry perl https://raw.githubusercontent.com/wet-boew/wet-boew-wpss/master/README.md 
the googlecode link is broken
here is the correct link
http://strawberryperl.com/download/5.18.0.1/strawberry-perl-5.18.0.1-64bit.msi

*EDIT*
actually, it's the 32 bit version according to README.md
here is the link to the 32 bit version **http://strawberryperl.com/download/5.18.1.1/strawberry-perl-5.18.1.1-32bit.msi**

also, this is an older version, is it still recommended?

**Comment by irwink** [comment]
The link has been corrected.
The supported versions of Strawberry Perl are from version 5.18 to version 5.24.  Version 5.26 is not supported as it is missing some required modules.
