### ISSUE TITLE
WPSS_Tool 6.8.0 Installation failure on Windows 7 64 bit using 32 bit perl

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-wpss#95]
I installed the python dependency as recommended on the README.md 
I installed perl 5.0.18 32 bit

my system: windows 7 64 bit

The GUI failed with Win32::GUI install failed

looked deeper into the logs, here is what the install log says:
```
Perl 5.018 installed on system
Check for Win32::GUI
Installing Win32-GUI-1.06
perl.exe Makefile.PL
Output of perl.exe Makefile.PL


dmake
Output of dmake
dmake:  Error: -- No target


dmake install
Output of dmake install
dmake:  Error: -- Don't know how to make `install'


install Win32::GUI complete
Check for Win32::GUI after install
Win32::GUI install failed
```

**Comment by joejoseph00** [comment]
I attempted to take the binary stuff over to my Linux machine to run my Dockerfile install but when I run docker build , it builds ok, but when I run the docker container I get this error:
standard_init_linux.go:178: exec user process caused "no such file or directory" , not sure if this is because my Dockerfile is incorrect or if the binaries it's using are incomplete because the windows installation failed.

**Comment by joejoseph00** [comment]
**dmake:  Error: -- Don't know how to make `install'**

**Comment by joejoseph00** [comment]
trying a newer version of perl... not sure if that will help

**Comment by joejoseph00** [comment]
perl 5.0.24 also fails.  
```
Perl 5.024 installed on system
Check for Win32::GUI
Installing Win32-GUI-1.06
perl.exe Makefile.PL
Output of perl.exe Makefile.PL


dmake
Output of dmake
dmake:  Error: -- No target


dmake install
Output of dmake install
dmake:  Error: -- Don't know how to make `install'


install Win32::GUI complete
Check for Win32::GUI after install
Win32::GUI install failed
```

Anything else I might be missing from the installation instructions?

**Comment by joejoseph00** [comment]
do I need the 64 bit version for win 7 64 ? or is there a missing dependency somewhere

**Comment by joejoseph00** [comment]
To clarify, it is the WPSS_tool installer that throws the error Win32::GUI install failed , apparently because dmake doesn't know how to make 'install'

**Comment by irwink** [comment]
Perl installation must be 32 bit, not 64.  The 64 bit installation does not support the Win32::GUI module.

**Comment by joejoseph00** [comment]
Ok, I chose 32 bit perl and if I recall correctly, 32 bit python, so maybe a windows 7 64 bit issue?    I installed python 2.7.6 from the link in the README.md http://python.org/ftp/python/2.7.6/python-2.7.6.msi  , have you ever installed this on a 64 bit windows machine ?

**Comment by joejoseph00** [comment]
all I was doing this for was to get the install folder files to copy over to a linux machine to use wpss from a Docker image.  Is there a make file for the source code to run on Linux?   I don't want the windows binaries

**Comment by irwink** [comment]
The release package here on GitHub is for a Windows installation, not Linux.  The program can be packaged for Linux for command line use only (i.e. no GUI).

**Comment by joejoseph00** [comment]
Hi @irwink what is the make command for building the Linux package?  It is required by the Dockerfile in the pull request I just made https://github.com/wet-boew/wet-boew-wpss/pull/97

**Comment by joejoseph00** [comment]
I guess we can close this issue, maybe open a new issue for the make command for building the Linux package.

**Comment by joejoseph00** [comment]
I'm using Linux, so all that matters is the build package for Linux however a workaround is to take the install folder from a windows install and put it on linux, add execute permissions to all the .py and .pl files
